[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self' https: http: data: blob:;
    script-src 'self' 'unsafe-inline' 'unsafe-eval' https: http: blob:;
    script-src-elem 'self' 'unsafe-inline' 'unsafe-eval' https: http: blob:;
    connect-src * https: http: wss: ws: blob:;
    img-src * data: blob: https: http:;
    style-src 'self' 'unsafe-inline' https: http:;
    font-src 'self' data: https:;
    worker-src blob: 'self';
    media-src *;
    frame-src *;
    object-src 'none';
  """
