[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  # FULL CSP FIX
  Content-Security-Policy = """
    default-src 'self' https: http: data: blob:;
    script-src 'self' 'unsafe-inline' 'unsafe-eval' https: http:;
    script-src-elem 'self' 'unsafe-inline' 'unsafe-eval' https: http:;
    connect-src * data: blob: https: http:;
    img-src * data: blob: https:;
    style-src 'self' 'unsafe-inline' https:;
    font-src 'self' https: data:;
    frame-src *;
    object-src 'none';
  """
